language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm version minor --no-git-tag-version
  - binder publish-local
after_success:
  - chmod +x release-site.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./release-site.sh
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
