language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm version minor --no-git-tag-version
  - binder publish-quest
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.travis/push-changes-to-master.sh
notifications:
  email:
    recipients:
      - your.name@yourcompany.com
    on_success: [change]
    on_failure: [always]

